#Secret
---
apiVersion: v1
kind: Secret
metadata:
  name: actividad-grupo5-secret
type: Opaque
stringData:
  config.yaml: |
    apiUrl: "https://api.privada.cl"
    username: <user>
    password: <password>